### PR TITLE
Serialization

### PR DESCRIPTION
**Pull request by jmirabel**
Requires https://github.com/humanoid-path-planner/hpp-util/pull/22

### CODE REVIEW

**Comment by nim65s** [comment]
I don't underestand how, but github found out that 7be6f5d0dbc36efa52ce2449b693149a563f10a6 would fix #125 . Thanks for this fix :)

**Comment by jmirabel** [comment]
> I don't underestand how, but github found out

No mystery. I used the *Linked issues* panel on the left.

**Comment by nim65s** [comment]
I see, thanks :)

**Comment by jmirabel** [comment]
Last commit fixes compatibility with Pinocchio < 2.4.5 (not released yet :) ). This PR needs https://github.com/stack-of-tasks/pinocchio/pull/1213 to be functional.

**Pull request merged**
