### PR TITLE
Code cleaning + documentation cleaning.

### PR DESCRIPTION
**Pull request by jmirabel**
Related to https://github.com/humanoid-path-planner/hpp-doc/pull/33

### CODE REVIEW

**Comment by jmirabel** [comment]
@pFernbach This removes some deprecated methods. I believe you fixed in hpp-rbprm the calls to the deprecated API. Am I correct ?
If yes, then this PR should not impact you.

**Comment by pFernbach** [comment]
In hpp-rbprm yes, but I didn't check hpp-rbprm-corba yet. I'll do it soon.

**Comment by pFernbach** [comment]
Done, rbprm-corba is clean of deprecated warnings.

**Comment by jmirabel** [comment]
Perfect, thanks.

**Pull request merged**
