### PR TITLE
Synchronize with recent modifications of Pinocchio API + fix some warnings

### PR DESCRIPTION
**Pull request by jcarpent**

### CODE REVIEW

**Comment by florent-lamiraux** [comment]
Test tconfiguration does not compile on my machine.
I am up to date on devel branch in pinocchio.

**Comment by jcarpent** [comment]
I'm not able to compile this unit test because it relies on romeo_description which depends on ROS itself.

Can you show off the lines where the tests fail?

**Comment by jmirabel** [comment]
I will have a look. Three weeks ago, the tests was passing: https://gepgitlab.laas.fr/humanoid-path-planner/hpp-doc/-/jobs/3470

**Comment by jmirabel** [comment]
The issue has nothing to do with the changes @jcarpent made. The problem is the following.

Consider a free-floating robot, with bounds on translations. Let q0 and q1 are two configurations within the bounds and such that the canonical path in SE(3) between the two goes out of bounds. This is possible since the path does not correspond to a straight line in R^3.
Let v be `q1-q0`. Then, `q0 + t * v` may not be within joint bound for all t in `[0,1]`. `interpolate` and `integrate<false, ...>` do not saturate the joint bound while `integrate<true, ...>` does. Thus there can be a difference between `interpolate(q0,q1,0.5)` and `integrate(q0,0.5*v)`...

**Comment by florent-lamiraux** [comment]
Nicely found.

**Comment by jmirabel** [comment]
Did you take the last commit I pushed (947f86f) ?

**Pull request merged**
