### PR TITLE
Modified the subtree center of mass

### PR DESCRIPTION
**Pull request by nmansard**
Modified the main algo.
Added unittest to validate it against the classical Jcom and by finite differencing.

It seems to work fine, except for a minor problem with the finite-diff, probably coming from Pinocchio itself, that will be investigated later.

### CODE REVIEW

**Comment by jmirabel** [comment]
I assumed all the information are expressed in the world frame.

The 3x3 identity at the beginning of the Jacobian obtained by finite difference makes sense to me whereas the non-identity from the `CenterOfMassComputation` makes no sense.
Shifting the full robot of a given translation shifts accordingly the COM.

**Comment by jmirabel** [comment]
The rotation that transform one Jacobian to the other is exactly the rotation of the root joint.

**Comment by nmansard** [comment]
Yes of course it is. The robot root velocity is expressed in the frame of the first body ("root" frame), while the com velocity is expressed in the world frame. You must have this rotation in the three first columns. I do not get why we do not find it by finite differencing. I guess we should investigate the pinocchio::integrate method.

**Comment by jcarpent** [comment]
I added the subtree com inside Pinocchio. Please refer to https://github.com/jcarpent/pinocchio/tree/topic/subtree-com. I think it is better to locate it inside Pinocchio and avoid duplicated codes.

**Comment by jmirabel** [comment]
I understand, thanks !

**Comment by nmansard** [comment]
Lets merge this one first, and see what is in Pinocchio in another PR.

**Pull request merged**
